language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "6.0"
script:
  - npm test
addons:
  apt:
    packages:
      - build-essential
      - g++
      - libcairo2-dev
      - libgif-dev
      - libjpeg-dev
      - libpango1.0-dev
      - make
      - python
